In [2]:
import numpy as np
import matplotlib.pyplot as plt

## Opgave 4.1

Går med følgende defintioner:
$$
A \in \mathbb{R}^{m \times n}, \; B,C \in \mathbb{R}^{n \times r}, \; D \in \mathbb{R}^{r \times m}
$$

In [26]:
m = 1000
n = 70
r = 3000
A = np.ones((m,n))
B, C = np.ones((n,r)), np.ones((n,r))
D = np.ones((r, m))

In [27]:
def product_flops(M1,M2):
    S1 = M1.shape
    S2 = M2.shape
    return S1[0] * S2[1] * 2 * S2[0]

In [28]:
def sum_flops(M1,M2):
    S1 = M1.shape
    return S1[0] * S1[1]

### (a)

In [29]:
flop_amount = product_flops(A,B)

print(f"AB kræver {flop_amount} flops")

AB kræver 420000000 flops


### (b)

In [30]:
flop_amount = product_flops(A, B+C) + sum_flops(B,C)

print(f"A(B + C) kræver {flop_amount} flops")

A(B + C) kræver 420210000 flops


### (c)

In [31]:
flop_amount = product_flops(C, D) + product_flops(C@D, A)

print(f"(CD)A kræver {flop_amount} flops")

(CD)A kræver 429800000 flops


### (d)

In [32]:
flop_amount = product_flops(D, A) + product_flops(C, D@A)

print(f"C(DA) kræver {flop_amount} flops")

C(DA) kræver 449400000 flops


### (e)

In [33]:
BD = B @ D
flop_amount = product_flops(B, D) + product_flops(A, BD) + product_flops(A@BD, A)

print(f"(A(BD))A kræver {flop_amount} flops")

(A(BD))A kræver 700000000 flops


### (f)

In [34]:
AB = A @ B
DA = D @ A
flop_amount = product_flops(A, B) + product_flops(D, A) + product_flops(AB, DA)

print(f"(AB)(DA) kræver {flop_amount} flops")

(AB)(DA) kræver 1260000000 flops


### (g)

In [35]:
DA = D @ A
flop_amount = product_flops(D, A) + product_flops(B, DA) + product_flops(A, B@DA)

print(f"A(B(DA)) kræver {flop_amount} flops")

A(B(DA)) kræver 459200000 flops


## Opgave 4.2

### (a)

Finder indgang 2 i første akse og sætter derefter indgangene 1, 3, 4 og 6 til 1 i anden akse.

### (b)

Finder indgang 1,4 og 2,6 og ændrer dem til hhv. 5 og 7

### (c)

Bytter om på alle værdier fra anden akses indgang 1 og 3

### (d)

Finder indgangene fra 2 til 5 (5 ekslukderet) i første akse og ændrer værdierne i rækkefølge til hhv. 0, 1 og 2.

### (e)

Finder ingang 4 i første akse. Derefter plusses hver anden indgang i anden akse med 6, hvor det starter fra 3 og slutter på 8 (8 eklsuderet).

### (f)

Ingen ide.

Ingen ide om ulempen ved at skrive a[2][3] istedet for a[2,3]

## Opgave 4.3

### (a)

In [10]:
ligning_a = np.array([  [2, -3, 7],
                        [1, 2, -2]], dtype=float)

print(ligning_a)

[[ 2. -3.  7.]
 [ 1.  2. -2.]]


In [11]:
# R0 <-> R1
ligning_a[ [0,1], : ] = ligning_a[ [1,0], : ]

print(ligning_a)

[[ 1.  2. -2.]
 [ 2. -3.  7.]]


In [12]:
# R1 -> R1 - 2R0
ligning_a[1, :] -= 2 * ligning_a[0, :]

print(ligning_a)

[[ 1.  2. -2.]
 [ 0. -7. 11.]]


In [13]:
# R1 -> -1/7 * R1
ligning_a[1, :] *= 1/ligning_a[1,1]

print(ligning_a)

[[ 1.          2.         -2.        ]
 [-0.          1.         -1.57142857]]


In [14]:
# R0 -> R0 - 2R1
ligning_a[0, :] -= 2 * ligning_a[1, :]

print(ligning_a)

[[ 1.          0.          1.14285714]
 [-0.          1.         -1.57142857]]


In [15]:
x_a, y_b = ligning_a[:,2]

print(f"Løsningen til ligning a er: x = {x_a}, y = {y_b}")

Løsningen til ligning a er: x = 1.1428571428571428, y = -1.5714285714285714


### (b)

In [16]:
ligning_b = np.array([  [2, 1, -2, 1],
                        [1, -2, 1, -1],
                        [2, 4, 2, 0]], dtype=float)

print(ligning_b)

[[ 2.  1. -2.  1.]
 [ 1. -2.  1. -1.]
 [ 2.  4.  2.  0.]]


In [17]:
# R0 <-> R1
ligning_b[ [0,1], : ] = ligning_b[ [1,0], : ]

print(ligning_b)

[[ 1. -2.  1. -1.]
 [ 2.  1. -2.  1.]
 [ 2.  4.  2.  0.]]


In [18]:
# R1 -> R1 - 2R0
ligning_b[1, :] -= 2 * ligning_b[0, :]

print(ligning_b)

[[ 1. -2.  1. -1.]
 [ 0.  5. -4.  3.]
 [ 2.  4.  2.  0.]]


In [19]:
# R1 -> 1/5 * R1
ligning_b[1, :] *= 1/ligning_b[1,1]

print(ligning_b)

[[ 1.  -2.   1.  -1. ]
 [ 0.   1.  -0.8  0.6]
 [ 2.   4.   2.   0. ]]


In [20]:
# R2 -> R2 - 2R0
ligning_b[2, :] -= 2 * ligning_b[0, :]

print(ligning_b)

[[ 1.  -2.   1.  -1. ]
 [ 0.   1.  -0.8  0.6]
 [ 0.   8.   0.   2. ]]


In [21]:
# R2 -> R2 - 8R1
ligning_b[2, :] -= 8 * ligning_b[1, :]

print(ligning_b)

[[ 1.  -2.   1.  -1. ]
 [ 0.   1.  -0.8  0.6]
 [ 0.   0.   6.4 -2.8]]


In [22]:
# R2 -> 1/6.4 R2
ligning_b[2, :] *= 1/ligning_b[2,2]

print(ligning_b)

[[ 1.     -2.      1.     -1.    ]
 [ 0.      1.     -0.8     0.6   ]
 [ 0.      0.      1.     -0.4375]]


In [23]:
# R1 -> R1 + (4/5 R2)
ligning_b[1, :] += 4/5 * ligning_b[2, :]

print(ligning_b)

[[ 1.     -2.      1.     -1.    ]
 [ 0.      1.      0.      0.25  ]
 [ 0.      0.      1.     -0.4375]]


In [24]:
# R0 -> R0 + 2R1
ligning_b[0, :] += 2 * ligning_b[1, :]

print(ligning_b)

[[ 1.      0.      1.     -0.5   ]
 [ 0.      1.      0.      0.25  ]
 [ 0.      0.      1.     -0.4375]]


In [25]:
# R0 -> R0 - R2
ligning_b[0, :] -= ligning_b[2, :]

print(ligning_b)

[[ 1.      0.      0.     -0.0625]
 [ 0.      1.      0.      0.25  ]
 [ 0.      0.      1.     -0.4375]]


In [26]:
x_b, y_b, z_b = ligning_b[:,3]

print(f"Løsningen til ligning b er: x = {x_b}, y = {y_b}, z = {z_b}")

Løsningen til ligning b er: x = -0.06249999999999989, y = 0.25, z = -0.4375000000000001


Taget i betragning at der er en løsning for præcis 

### (c)

In [27]:
ligning_c = np.array([  [2, -1, 2, 0],
                        [1, 1, -1, 3],
                        [0, 0,  0, 0]], dtype=float)

print(ligning_c)

[[ 2. -1.  2.  0.]
 [ 1.  1. -1.  3.]
 [ 0.  0.  0.  0.]]


In [28]:
# R0 <-> R1
ligning_c[ [0,1], : ] = ligning_c[ [1,0], : ]

print(ligning_c)

[[ 1.  1. -1.  3.]
 [ 2. -1.  2.  0.]
 [ 0.  0.  0.  0.]]


In [29]:
# R1 -> R1 - 2R0
ligning_c[1, :] -= 2 * ligning_c[0, :]

print(ligning_c)

[[ 1.  1. -1.  3.]
 [ 0. -3.  4. -6.]
 [ 0.  0.  0.  0.]]


In [30]:
# R1 -> -1/3 * R1
ligning_c[1, :] *= 1/ligning_c[1,1]

print(ligning_c)

[[ 1.          1.         -1.          3.        ]
 [-0.          1.         -1.33333333  2.        ]
 [ 0.          0.          0.          0.        ]]


In [31]:
# R0 -> R0 - R1
ligning_c[0, :] -= ligning_c[1, :]

print(ligning_c)

[[ 1.          0.          0.33333333  1.        ]
 [-0.          1.         -1.33333333  2.        ]
 [ 0.          0.          0.          0.        ]]


z er fri. Den generelle løsning er:
$$
x = 1 - \frac{1}{3} z, \; y = 2 + \frac{4}{3} z, \; z \in \mathbb{Z}
$$

## Opgave 4.4

### (a)

In [32]:
a = 10
b = 8
c = 5
d = 6

#### (i)

In [33]:
# Alle ligninger er på formen we + xf + yh + zg = n
ligning_efgh = np.array([  [0, -1, 1, 0, a],
                           [0, 0, 1, -1, b],
                           [-1, 1, 0, 0, c],
                           [-1, 0, 0, 1, d]], dtype=float)

print(ligning_efgh)

[[ 0. -1.  1.  0. 10.]
 [ 0.  0.  1. -1.  8.]
 [-1.  1.  0.  0.  5.]
 [-1.  0.  0.  1.  6.]]


In [34]:
# R0 <-> R3
ligning_efgh[ [0,3], : ] = ligning_efgh[ [3,0], : ]

print(ligning_efgh)

[[-1.  0.  0.  1.  6.]
 [ 0.  0.  1. -1.  8.]
 [-1.  1.  0.  0.  5.]
 [ 0. -1.  1.  0. 10.]]


In [35]:
# R0 -> R0 - 2R2
ligning_efgh[0, :] -= 2 * ligning_efgh[2, :]

print(ligning_efgh)

[[ 1. -2.  0.  1. -4.]
 [ 0.  0.  1. -1.  8.]
 [-1.  1.  0.  0.  5.]
 [ 0. -1.  1.  0. 10.]]


In [36]:
# R1 <-> R3
ligning_efgh[ [1,3], : ] = ligning_efgh[ [3,1], : ]

print(ligning_efgh)

[[ 1. -2.  0.  1. -4.]
 [ 0. -1.  1.  0. 10.]
 [-1.  1.  0.  0.  5.]
 [ 0.  0.  1. -1.  8.]]


In [37]:
# R1 -> -1 * R1
ligning_efgh[1, :] *= -1

print(ligning_efgh)

[[  1.  -2.   0.   1.  -4.]
 [ -0.   1.  -1.  -0. -10.]
 [ -1.   1.   0.   0.   5.]
 [  0.   0.   1.  -1.   8.]]


In [38]:
# R2 <-> R3
ligning_efgh[ [2,3], : ] = ligning_efgh[ [3,2], : ]

print(ligning_efgh)

[[  1.  -2.   0.   1.  -4.]
 [ -0.   1.  -1.  -0. -10.]
 [  0.   0.   1.  -1.   8.]
 [ -1.   1.   0.   0.   5.]]


In [39]:
# R3 -> R3 + R0
ligning_efgh[3, :] += ligning_efgh[0, :]

print(ligning_efgh)

[[  1.  -2.   0.   1.  -4.]
 [ -0.   1.  -1.  -0. -10.]
 [  0.   0.   1.  -1.   8.]
 [  0.  -1.   0.   1.   1.]]


In [40]:
# R3 -> R3 + R1
ligning_efgh[3, :] += ligning_efgh[1, :]

print(ligning_efgh)

[[  1.  -2.   0.   1.  -4.]
 [ -0.   1.  -1.  -0. -10.]
 [  0.   0.   1.  -1.   8.]
 [  0.   0.  -1.   1.  -9.]]


In [41]:
# R3 -> R3 + R2
ligning_efgh[3, :] += ligning_efgh[2, :]

print(ligning_efgh)

[[  1.  -2.   0.   1.  -4.]
 [ -0.   1.  -1.  -0. -10.]
 [  0.   0.   1.  -1.   8.]
 [  0.   0.   0.   0.  -1.]]


Da echelonformen af matricen har en række på formen [0 0 ... 0 |1] betyder det, at systemet ikke har nogen løsninger.

#### (ii)

#### (iii)

### (b)

### (c)

## Opgave 4.5

### (a)

In [42]:
u = np.array([1, -1, 2])[:, np.newaxis]
v = np.array([1, 2, -2, -2])[:, np.newaxis]

print(f"u:\n{u}\n")
print(f"v:\n{v}")

u:
[[ 1]
 [-1]
 [ 2]]

v:
[[ 1]
 [ 2]
 [-2]
 [-2]]


In [43]:
A = u @ v.T

print(A)

[[ 1  2 -2 -2]
 [-1 -2  2  2]
 [ 2  4 -4 -4]]


In [44]:
# R1 -> R1 + R0
A[1, :] += A[0, :]

print(A)

[[ 1  2 -2 -2]
 [ 0  0  0  0]
 [ 2  4 -4 -4]]


In [45]:
# R2 -> R2 - 2R0
A[2, :] -= 2 * A[0, :]

print(A)

[[ 1  2 -2 -2]
 [ 0  0  0  0]
 [ 0  0  0  0]]


Der er en enkel pivotelement i echelonformen for A.

### (b)

Der kan maksimalt være 1 pivotelement i echelonformen for $B$.

### (c)

Der kan maksimalt være 3 pivotelementer i echelonformen for $C$.

For at sikre, at der er præcis 2 skal der først være en nulrække til sidst. Dette forekommer hvis $u_{2}$ og $w_{2}$ er 0. I forlængelse skal enten $u$ eller $w$'s andre koordinater være andet end 0. Derefter er der rimeligt frit spil, men en simpel måde at sikre det på, er at hele $w$ kan sættes til 0. Derefter skal $u_{0}$ bare være en værdi der ikke går op i $u_{1}$ eller omvendt. Selvfølgelig skal $v$ også have værdier, som ikke er 0.

In [10]:
u = np.array([1, 2, 3])[:, np.newaxis]
v = np.array([6, 5, 2])[:, np.newaxis]
w = np.array([2, 4, 6])[:, np.newaxis]
x = np.array([1, 5, 8])[:, np.newaxis]

a = u @ v.T + w @ x.T
a

array([[ 8, 15, 18],
       [16, 30, 36],
       [24, 45, 54]])

In [11]:

a[1, :] -= 2* a[0, :]
a

array([[ 8, 15, 18],
       [ 0,  0,  0],
       [24, 45, 54]])

In [12]:
a[2, :] -= 3* a[0, :]
a

array([[ 8, 15, 18],
       [ 0,  0,  0],
       [ 0,  0,  0]])