In [26]:
import numpy as np
import sympy as sp

## (a) Bekræft at $A$ er symmetrisk og forklar hvorfor $A$ er diagonaliserbar med kun reelle egenværdier. {-}

Det kan ses i afsnit 8.3 af notesættet at en symmetrisk matrix vil være lig den selv transponeret. For at bekræfte at $A$ er symmetrisk kan denne egenskab da tjekkes.

In [27]:
A = np.array([  [0.5, 0.25, 0.25],
                [0.25, 0.3, 0.45],
                [0.25, 0.45, 0.3]])

np.all(A == A.T)    # A er symmetrisk hvis dette giver "True"

True

Sætning 23.10 fra notesættet fortæller, at så længe $A$ er symmetrisk, findes der en ortogonal matrix $V$ således at:
$$
A = V \Lambda V^{T}
$$
Hvis et sådan udtryk kan opstilles er $A$ per definition diagonaliserbar jvf. definition 21.7.

Ud fra Lemma 23.13 vides det også at alle egenværdier for $A$ må være indenfor de reelle tal, da $A$ er symmetrisk.

$\pagebreak$

## (b) Bekræft at 1,0 er en egenværdi for $A$, og bestem derefter de andre egenværdier for $A$. {-}

Det karakteristiske polynomium sættes op som vist i afsnit 21.5 af notesættet.
\begin{align*}
\text{det}(A - \lambda I_{3}) & = \text{det}\left( \begin{bmatrix}
0.5 - \lambda & 0.25 & 0.25 \\
0.25 & 0.3 - \lambda & 0.45 \\
0.25 & 0.45 & 0.3 - \lambda
\end{bmatrix} \right)\\
 & = (0.5 - \lambda) \text{det} \left(\begin{bmatrix}
0.3 - \lambda & 0.45 \\
0.45 & 0.3 - \lambda
\end{bmatrix}\right) - 0.25 \, \text{det} \left(\begin{bmatrix}
0.25 & 0.45 \\
0.25 & 0.3 - \lambda
\end{bmatrix}\right) + 0.25 \, \text{det} \left(\begin{bmatrix}
0.25 & 0.3 - \lambda \\
0.25 & 0.45
\end{bmatrix}\right)\\
 & = (0.5 - \lambda) ((0.3 - \lambda)^{2} - 0.45^{2}) - 0.25 (0.25 (0.3 - \lambda) - 0.25 \cdot 0.45) + 0.25 (0.25 \cdot 0.45 - 0.25 (0.3 - \lambda))
\end{align*}

Dette kan reduceres til et tredjegradspolynomium, hvorefter det kan sættes lig 0 for at finde rødderne og dermed egenværdierne. Både reduktionen og løsningen af ligningen gøres med sympy som CAS-værktøj forneden.

In [28]:
lam = sp.symbols('lambda')

polynomium = (0.5 - lam) * ((0.3 - lam)**2 - 0.45**2) - 0.25 * (0.25 * (0.3 - lam) - 0.25 * 0.45) + 0.25 * (0.25 * 0.45 - 0.25 * (0.3 - lam))
lambda_0, lambda_1, lambda_2 = sp.solve(polynomium, lam)
lambda_0, lambda_1, lambda_2 = float(lambda_0), float(lambda_1), float(lambda_2)
lambda_0, lambda_1, lambda_2

(-0.15, 0.25, 1.0)

Det kan her ses, at 1.0 er en egenværdi for $A$

$\pagebreak$

## (c) Beregn en ortonormal basis for $\mathbb{R}^{3}$ bestående af egenvektorer for $A$. {-}

Først findes egenvektorerne for $A$ ved at løse ligningssystemet $(A - \lambda I_{3}) v = 0$ for hver egenværdi.

In [29]:
ligning_0 = A - lambda_0 * np.eye(3)
ligning_0[0] *= 1 / ligning_0[0, 0]
ligning_0[2] -= ligning_0[1]
ligning_0[1] -= 1/4 * ligning_0[0]
np.round(ligning_0, 4)

array([[ 1.    ,  0.3846,  0.3846],
       [ 0.    ,  0.3538,  0.3538],
       [ 0.    ,  0.    , -0.    ]])

In [30]:
ligning_1 = A - lambda_1 * np.eye(3)
ligning_1[1] -= ligning_1[0]
ligning_1[2] -= ligning_1[0]
ligning_1[2] += ligning_1[1]
ligning_1

array([[ 0.25,  0.25,  0.25],
       [ 0.  , -0.2 ,  0.2 ],
       [ 0.  ,  0.  ,  0.  ]])

In [31]:
ligning_2 = A - lambda_2 * np.eye(3)
ligning_2[0] *= -2
ligning_2[1] -= 1/4 * ligning_2[0]
ligning_2[2] -= 1/4 * ligning_2[0]
ligning_2[2] += ligning_2[1]
ligning_2


array([[ 1.   , -0.5  , -0.5  ],
       [ 0.   , -0.575,  0.575],
       [ 0.   ,  0.   ,  0.   ]])

In [32]:
# Løsninger til de forskellige egenværdier kan være disse
v_0 = np.array([0, -1, 1])[:, np.newaxis]
v_1 = np.array([-2, 1, 1])[:, np.newaxis]
v_2 = np.array([1, 1, 1])[:, np.newaxis]

$\pagebreak$

Ifølge proposition 21.5 af notesættet vil egenvektorerne være en basis, hvis mængden af egenvektorer og -værdier svarer til matricens dimensioner. Ud fra de fundne egenvektorer kan en basis af $\mathbb{R}^{3}$ være:

In [33]:
V = np.column_stack([v_0/np.linalg.norm(v_0), v_1/np.linalg.norm(v_1), v_2/np.linalg.norm(v_2)])
V

array([[ 0.        , -0.81649658,  0.57735027],
       [-0.70710678,  0.40824829,  0.57735027],
       [ 0.70710678,  0.40824829,  0.57735027]])

$\pagebreak$

## (d) Bestem en ortogonalmatrix $V$ og en diagonalmatrix $Λ$ således at {-}
$$
A = V \Lambda V^{T}
$$

Den den ortogonale matrix $V$ er allerede opsat i forrige opgave, og diagnoalmatricen kan opstilles ud fra egenværdierne fra tidligere. Numpy kan derefter bruges til at tjekke om $A$ faktisk svarer til den dekomponering, som er blevet opstillet.

In [34]:
Lambda = np.diag((lambda_0, lambda_1, lambda_2))

# Tjekker om de er det samme indenfor machine epsilon
machine_epsilon = np.finfo(float).eps
np.allclose(A, V @ Lambda @ V.T, rtol = machine_epsilon, atol = machine_epsilon)

True

## (e) For {-}
$$
v =
\begin{bmatrix}
0.1 \\
0.2 \\
0.4
\end{bmatrix}
$$
brug dine resultater til at bestemme grænsen af $A^{k}v$ for $k \to \infty$.

Udtrykket for $A^{k}v$ kan omskrives vha. dekomponeringen fra forrige opgave. Beviset for at kun diagonalmatricen skal sættes i $k$'te potens kan ses i eksempel 20.6 af notesættet. Udtrykket bliver da følgende:
$$
A^{k} v = V \Lambda^{k} V^{T} v
$$
Det kan ses at kun diagonalmatricen afhænger af k, hvilket betyder at det kun er den som der skal findes en grænseværdi for. Grænseværdien kommer til at være følgende:
$$
\lim_{ k \to \infty } \Lambda^{k}
=
\lim_{ k \to \infty } 
\begin{bmatrix}
-0.15^{k} & 0 & 0 \\
0 & 0.25^{k} & 0 \\
0 & 0 & 1^{k}
\end{bmatrix}
=
\begin{bmatrix}
0 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 1^{k}
\end{bmatrix}
$$
Dette kan indsættes i omskrivningen af $A^{k}v$ for at finde grænseværdien for den for $k \to \infty$, hvilekt gøres i numpy forneden.

In [35]:
v = np.array([0.1, 0.2, 0.4])[:, np.newaxis]
Lambda_k = np.diag((0, 0, 1))

print("Grænseværdien for udtrykket er:\n", V @ Lambda_k @ V.T @ v)

Grænseværdien for udtrykket er:
 [[0.23333333]
 [0.23333333]
 [0.23333333]]
