In [9]:
import numpy as np

Betragt vektorerne
$$
v_{0} = 
\begin{bmatrix}
1.0 \\
-1.0 \\
1.0 \\
-1.0
\end{bmatrix}, \qquad
v_{1} =
\begin{bmatrix}
1.0 \\
1.0 \\
-1.0 \\
-1.0
\end{bmatrix}, \qquad
v_{2} =
\begin{bmatrix}
0.0 \\
2.0 \\
2.0 \\
0.0
\end{bmatrix}
$$
i $\mathbb{R}^{4}$.

## (a) {-}

Dan Grammatricen for $v_{0}$, $v_{1}$, $v_{2}$ og bekræft at denne samling vektorer er
ortogonal.

In [10]:
# Definerer samling af vektorer
v0 = np.array([1, -1, 1, -1], dtype=float)[:, np.newaxis]
v1 = np.array([1, 1, -1, -1], dtype=float)[:, np.newaxis]
v2 = np.array([0, 2, 2, 0], dtype=float)[:, np.newaxis]
V = np.column_stack([v0, v1, v2])

# Definerer grammatricen ud fra samlingen
G = V.T @ V
print(G)

[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 8.]]


Da Grammatricen kun har værdier forskellig fra nul i diagonalen, betyder det at samlingen er ortogonal.

$\pagebreak$

## (b) {-}

Beregn projektionen $Px$ af
$$
x =
\begin{bmatrix}
4.0 \\
3.0 \\
2.0 \\
1.0
\end{bmatrix}
$$
på samlingen $v_{0}, v_{1}, v_{2}$.

In [11]:
# Definerer den givne x-vektor
x = np.array([4, 3, 2, 1], dtype=float)[:, np.newaxis]

# Definerer projektionsmatricen
P = (v0 @ v0.T) / np.linalg.norm(v0)**2 + (v1 @ v1.T) / np.linalg.norm(v1)**2 + (v2 @ v2.T) / np.linalg.norm(v2)**2

# Finder og printer x projeceret på vektor samlingen
print("Den projecerede vektor, Px, er:\n", P @ x)

Den projecerede vektor, Px, er:
 [[ 1.5]
 [ 3. ]
 [ 2. ]
 [-1.5]]


## (c) {-}

Bekræft at $v_{3} := x - Px$ er ortogonal til $v_{0}$, $v_{1}$ og $v_{2}$.

In [12]:
# Tilføjer den nye vektor oveni den gamle samling
v3 = x - P @ x
V_ny = np.column_stack([V, v3])

# Definerer en ny grammatrix
G_ny = V_ny.T @ V_ny
print(G_ny)

[[ 4.00000000e+00  0.00000000e+00  0.00000000e+00 -4.44089210e-16]
 [ 0.00000000e+00  4.00000000e+00  0.00000000e+00  4.44089210e-16]
 [ 0.00000000e+00  0.00000000e+00  8.00000000e+00  2.66453526e-15]
 [-4.44089210e-16  4.44089210e-16  2.66453526e-15  1.25000000e+01]]


Her står alle ikke diagonalerne ikke til at være præcis 0 fejl i float beregninger. Tages der forbehold for det kan det igen ses, at kun diagonalen har ikke nul værdier, hvilket betyder at samlingen med $v_{3}$ stadig er ortogonal.

$\pagebreak$

## (d) {-}

Brug $v_{0}, v_{1}, v_{2}, v_{3}$ til at bestemme en ortonormal basis for $\mathbb{R}^{4}$.

In [13]:
# Samlingen kan gøres ortonormal ved at dele vektorerne med deres længder 
V_normal = np.column_stack([v0/np.linalg.norm(v0), v1/np.linalg.norm(v1), 
                            v2/np.linalg.norm(v2), v3/np.linalg.norm(v3)])

# Igen dannes en grammatrix
G_normal = V_normal.T @ V_normal
print(G_normal)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00 -5.55111512e-17]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  5.55111512e-17]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  2.66453526e-16]
 [-5.55111512e-17  5.55111512e-17  2.66453526e-16  1.00000000e+00]]


Igen kan det ses, at kun diagonalerne i grammatricen har værdier forskellig fra 0. Dog kan det nu også ses at alle værdierne er lig 1, hvilket betyder at samlingen er ortonormal og dermed er en ortonormal basis for $\mathbb{R}^{4}$. Denne ortonormal basis kan ses for neden.

In [14]:
print("En ortonormal basis for R^4 kan være:\n", V_normal)

En ortonormal basis for R^4 kan være:
 [[ 5.00000000e-01  5.00000000e-01  0.00000000e+00  7.07106781e-01]
 [-5.00000000e-01  5.00000000e-01  7.07106781e-01  2.51214793e-16]
 [ 5.00000000e-01 -5.00000000e-01  7.07106781e-01  1.25607397e-16]
 [-5.00000000e-01 -5.00000000e-01  0.00000000e+00  7.07106781e-01]]
