In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Opgave 7.1

### (a)

In [4]:
u = np.array([1,-1,1])[:, np.newaxis]
v = np.array([-1,-2,1])[:, np.newaxis]
weight = np.array([7,2,3])[:, np.newaxis]

print(np.vdot(weight * u, v))

0


Siden det indre produkt er 0 vil u og v være ortogonal.

### (b)

In [6]:
w = np.array([1,0,0])[:, np.newaxis]

w_pr_u = np.vdot(w, weight * u) / np.linalg.norm(u)**2 * u
w_pr_v = np.vdot(w, weight * v) / np.linalg.norm(v)**2 * v

print("pr_u (w) =\n", w_pr_u, "\n")
print("pr_v (w) =\n", w_pr_v)

pr_u (w) =
 [[ 2.33333333]
 [-2.33333333]
 [ 2.33333333]] 

pr_v (w) =
 [[ 1.16666667]
 [ 2.33333333]
 [-1.16666667]]


### (c)

$$
A = 
\begin{bmatrix}
7 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 3
\end{bmatrix}
$$

$$
\begin{align*}
\left < 
\begin{bmatrix}
x_0  \\
x_1  \\
x_2
\end{bmatrix}
,
\begin{bmatrix}
y_0  \\
y_1  \\
y_2
\end{bmatrix}
\right>
& = 
x^T A y \\
& = 
[x_0, x_1, x_2] \begin{bmatrix}
7 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 3
\end{bmatrix} \begin{bmatrix}
y_0  \\
y_1  \\
y_2
\end{bmatrix} \\
& = 
7 x_0 y_0 + 2 x_1 y_1 + 3 x_2 y_2
\end{align*}
$$

## Opgave 7.2

### (a)

In [7]:
ligning_a = np.array([  [1, 1, 1],
                        [0, 1, 1],
                        [0, 0, 1]])

# Overflødigt
# # R0 -> R0 - R1
# ligning_a[0, :] -= ligning_a[1, :]

# # R1 -> R1 - R2
# ligning_a[1, :] -= ligning_a[2, :]

print(ligning_a)

[[1 1 1]
 [0 1 1]
 [0 0 1]]


Da alle rækker har pivotelementer er den lineær uafhængig.

### (b)

In [15]:
ligning_b = np.array([  [1, 1, 0],
                        [1, 0, 1],
                        [0, 1, 1]], dtype=float)

# R1 -> R1 - R0
ligning_b[1, :] -= ligning_b[0, :]

# R1 -> R1 * 1/-1
ligning_b[1, :] *= ligning_b[1, 1]

# R2 -> R2 - R1
ligning_b[2, :] -= ligning_b[1, :]

# R2 -> R2 * 1/2
ligning_b[2, :] *= 1 / ligning_b[2, 2]

print(ligning_b)

[[ 1.  1.  0.]
 [-0.  1. -1.]
 [ 0.  0.  1.]]


Da alle rækker har pivotelementer er den lineær uafhængig.

### (c)

In [9]:
ligning_c = np.array([  [1, -1,  0],
                        [-1, 0,  1],
                        [0,  1, -1]])

# R1 <-> R2
ligning_c[[1, 2], :] = ligning_c[[2, 1], :]

# R2 -> R2 + R0
ligning_c[2, :] += ligning_c[0, :]

# R2 -> R2 + R1
ligning_c[2, :] += ligning_c[1, :]

print(ligning_c)

[[ 1 -1  0]
 [ 0  1 -1]
 [ 0  0  0]]


Da den nederste række ikke har et pivotelement kan den ikke være lineær uafhægnig.

### (d)

In [10]:
ligning_d = np.array([  [1     , 1j    ,-1 + 1j],
                        [1j    , 1 - 1j, 1     ],
                        [1 + 1j, 1     , 1j    ]])

# R1 -> R1 - R2
ligning_d[1, :] -= ligning_d[2, :]

# R1 -> R1 + R0
ligning_d[1, :] += ligning_d[0, :]

# R2 <-> R1
ligning_d[[1, 2], :] = ligning_d[[2, 1], :]

print(ligning_d)

[[ 1.+0.j  0.+1.j -1.+1.j]
 [ 1.+1.j  1.+0.j  0.+1.j]
 [ 0.+0.j  0.+0.j  0.+0.j]]


Da den nederste række ikke har et pivotelement kan den ikke være lineær uafhægnig.

## Opgave 7.3

### (a)

In [11]:
# Ganger alle indgange sammen, sætter i anden, 
# summerer og tager kvadratrod
def frob_norm(M):
    sum = 0
    for row in M:
        for element in row:
            sum += element**2
    return np.sqrt(sum)

In [12]:
A = np.array([  [6, 0 ],
                [0, -3]])
B = np.array([  [ 1,  2],
                [-1, -2]])

print("||A||_F =\n", frob_norm(A), "\n")
print("||B||_F =\n", frob_norm(B))

||A||_F =
 6.708203932499369 

||B||_F =
 3.1622776601683795


In [14]:
print("<A, B> =", np.vdot(A, B))

<A, B> = 12


In [ ]:
print("<A, A> <= ", np.vdot(A, A))

## Opgave 7.4

### (a)

### (b)

### (c)

### (d)