In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Opgave 12.1

Find egenværdier

\begin{align*}

\text{det}(A - \lambda I_{2}) & = \text{det}\left( \begin{bmatrix}

7 - \lambda & 1 \\

6 & 2 - \lambda

\end{bmatrix} \right)\\

 & = (7 - \lambda) (2 - \lambda) - 1 \cdot 6 \\
 & = 14 - 7 \lambda - 2 \lambda + \lambda^{2} - 6 \\
 & = \lambda^{2} - 9 \lambda + 8
\end{align*}

\begin{align*}
\lambda & = \frac{-(-9) \pm \sqrt{ (-9)^{2} - 4 \cdot 1 \cdot 8 }}{2 \cdot 1} \\
 & = \frac{9 \pm \sqrt{ 81 - 32 }}{2} \\
 & = \frac{9 \pm 7}{2} \\
 & = 1 \; \lor \; 8 
\end{align*}

Find egenvektorer

$$
A - \lambda_{0} I_{2} =

\begin{bmatrix}
7 - 1 & 1 \\
6 & 2 - 1
\end{bmatrix}

=

\begin{bmatrix}
6 & 1 \\
6 & 1
\end{bmatrix}

\sim_{R_{2} \to R_{2} - R_{1}}

\begin{bmatrix}
6 & 1 \\
0 & 0
\end{bmatrix}
$$

Løs ligningerne
$$
6x + y = 0
$$

En løsning er
$$
v_{0} =
\begin{bmatrix}
-1 \\
6
\end{bmatrix}
$$



$$
A - \lambda_{1} I_{2} =

\begin{bmatrix}
7 - 8 & 1 \\
6 & 2 - 8
\end{bmatrix}

=

\begin{bmatrix}
-1 & 1 \\
6 & -6
\end{bmatrix}

\sim_{R_{2} \to R_{2} + 6 R_{1}}

\begin{bmatrix}
-1 & 1 \\
0 & 0
\end{bmatrix}
$$

Løs ligningerne

$$
-x + y = 0
$$

En løsning er

$$
v_{0} =
\begin{bmatrix}
1 \\
1
\end{bmatrix}
$$


## Opgave 12.2




$$
\begin{align*}
\text{det}(A - \lambda I_{3})
 & = \text{det}\left( \begin{bmatrix}
6 - \lambda & - 3 & 2 \\
0 & 2 - \lambda & 7 \\
0 & 0 & - 1 - \lambda
\end{bmatrix} \right) \\
 & = (6 - \lambda) \text{det} \left(\begin{bmatrix}
2 - \lambda & 7 \\
0 & - 1 - \lambda
\end{bmatrix}\right) 
+ 3 \, \text{det} \left(\begin{bmatrix}
0 & 7 \\
0 & - 1 - \lambda
\end{bmatrix}\right)
+ 2 \, \text{det} \left(\begin{bmatrix}
0 & 2 - \lambda \\
0 & 0
\end{bmatrix}\right)\\
 & = (6 - \lambda) (2 - \lambda) (- 1 - \lambda) + 3 (0) + 2 (0)\\
 & = (6 - \lambda) (2 - \lambda) (- 1 - \lambda)
\end{align*}
$$

$$
(6 - 6) (2 - 6) (- 1 - 6) = 0 \cdot (-4) \cdot (-7) = 0
$$

$$
(6 - 2) (2 - 2) (- 1 - 2) = 4 \cdot 0 \cdot (-3) = 0
$$

$$
(6 - (-1)) (2 - (-1)) (- 1 - (-1)) = 7 \cdot 3 \cdot 0 = 0
$$

For en vilkårlig diagonalmatrix ville man kunne stille det karakteristiske polynomium op på formen:
$$
(\sigma_{0} - \lambda) (\sigma_{1} - \lambda) (\sigma_{2} - \lambda)
$$
Derfor vil alle diagoalværdier være egenværdierne.

Den er diagonliserbar, da den er kvadratisk ($\mathbb{R}^{3 \times 3}$) og har 3 egenværdier og vektorer, hvilket betyder at den kan stilles på formen $A = V \Lambda V^{-1}$.



## Opgave 12.3

### (a)

In [2]:
u = np.array([1,2,4], dtype=float)[:,np.newaxis]
v = np.array([-1,2,1])[:,np.newaxis]
A = u @ v.T

print(A)

A[0] *= 1/A[0,0]
A[1] += 2 * A[0]
A[2] += 4 * A[0]
A

[[-1.  2.  1.]
 [-2.  4.  2.]
 [-4.  8.  4.]]


array([[ 1., -2., -1.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

Følgende ligninger opstilles:

$$
\begin{align*}
x_{0} - 2 x_{1} - x_{2} & = 0 \\
x_{0} = 2x_{1} + x_{2}
\end{align*}
$$

Den generelle løsning bliver:

$$
\begin{bmatrix}
x_{0} \\
x_{1} \\
x_{2}
\end{bmatrix}
=
\begin{bmatrix}
2x_{1} + x_{2} \\
x_{1} \\
x_{2}
\end{bmatrix}
=
x_{1}
\begin{bmatrix}
2 \\
1 \\
0
\end{bmatrix}
+
x_{2}
\begin{bmatrix}
1 \\
0 \\
1
\end{bmatrix}
$$

En basis for nulrummet kunne da være disse to vektorer:

$$
\begin{bmatrix}
2 \\
1 \\
0
\end{bmatrix}
,
\begin{bmatrix}
1 \\
0 \\
1
\end{bmatrix}
$$

### (b)


$$
A - 0 I_{3} =
\begin{bmatrix}
-1 & 2 & 1 \\
-2 & 4 & 2 \\
-4 & 8 & 4
\end{bmatrix}
=
\begin{bmatrix}
-1 & 2 & 1 \\
-2 & 4 & 2 \\
-4 & 8 & 4
\end{bmatrix}
\begin{cases}
\sim_{R_{1} \to R_{1} - 2 \cdot R_{0}} \\
\sim_{R_{2} \to R_{2} - 4 \cdot R_{0}}
\end{cases}
\begin{bmatrix}
-1 & 2 & 1 \\
0 & 0 & 0 \\
0 & 0 & 0
\end{bmatrix}
$$
Løs ligning
$$
-x + 2y + z = 0
$$
Det kan ses at hvis basisvektorerne for nulrummet indsættes i denne ligning, vil den være gyldig. Basisvektorerne er da både lineært uafhængige og egenvektorer for A med egenværdi 0.


### (c)

Egenværdien og vektoren kan indsættes i ligningen $(A - \lambda I_{n})v = 0$. Hvis der er en løsning er egenværdien fundet, og $u$ er en egenvektor.
$$
\begin{bmatrix}
-1 - \lambda & 2 & 1 \\
-2 & 4 - \lambda & 2 \\
-4 & 8 & 4 - \lambda
\end{bmatrix}
\begin{bmatrix}
1 \\
2 \\
4
\end{bmatrix}
=
0
$$
$$
-1-\lambda + 4 + 4 = 0 \Leftrightarrow \lambda = 7
$$
$$
-2 + 8 - 2 \lambda + 8 = 0 \Leftrightarrow \lambda = 7
$$
$$
-4 + 16 + 16 - 4 \lambda = 0 \Leftrightarrow \lambda = 7
$$

### (d)

Den er diagnoliserbar da den er i vektorummet $\mathbb{R}^{3}$ og har 3 egenvektorer.