In [18]:
import numpy as np
import matplotlib.pyplot as plt

# a) Bestemmelse af grammatricen for $v_0, v_1$ og $v_2$, og bekræftelse af at samlingen af vektorer er ortogonale

In [19]:
# Angivelse af vektorerne
v0 = np.array([1.0, -1.0, 1.0, -1.0]) [:, np.newaxis]
v1 = np.array([1.0, 1.0, -1.0, -1.0]) [:, np.newaxis]
v2 = np.array([0.0, 2.0, 2.0, 0.0]) [:, np.newaxis]

v0, v1, v2

(array([[ 1.],
        [-1.],
        [ 1.],
        [-1.]]),
 array([[ 1.],
        [ 1.],
        [-1.],
        [-1.]]),
 array([[0.],
        [2.],
        [2.],
        [0.]]))

In [20]:
# Angivelse af grammatricen
# For at lave en grammatrice, skal jeg først samle mine vektorer i en matrice, 
# hvor de indgår som søjlerne.
tM = np.hstack((v0, v1, v2))

tM

array([[ 1.,  1.,  0.],
       [-1.,  1.,  2.],
       [ 1., -1.,  2.],
       [-1., -1.,  0.]])

In [21]:
# Jeg kan nu bestemme grammatricen ud fra formlen: G = V^tV
G = tM.T @ tM
G

array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 8.]])

Af Lemma 9.8 i notesamlingen, så vil grammatricen, hvis den er identisk med identitetsmatricen, fortælle os at en samling af vektorer er ortonormal. 

I dette tilfælde er det tydeligt at se at dette ikke er tilfældet.

Dog har vi stadig en diagonal matrice, dertil kan man tænke sig frem til at indgangene [0,0], [1,1] og [2,2] vil være prikproduktet mellem henholdsvis <v1,v1>, <v2,v2> og <v3,v3>. 

Disse prikprodukter er det samme som 2-normen af vektorerne i 2., altså kan vi konkludere at samlingen ikke er en ortonormal samling, men dog er det en ortogonal samling, da længderne af vektorerne blot ikke er 1 for dem alle.

# b) Beregning af projektionen Px af x langs samlingen fra a)

Fra Definition 8.19 fra notesættet ved vi følgende:

Projektionen af $u$ på en ortogonal samling (hvilket vi har) er givet ved $Pu$, hvor $P$ er givet ved: 

$P = \frac{1}{||v_0||_2^2} * v_0v_0^T + \frac{1}{||v_1||_2^2} * v_1v_1^T + ... + \frac{1}{||v_{k-1}||_2^2} * v_{k-1}v_{k-1}^T$

In [22]:
# Bestemmelse af P:
P = (1/np.vdot(v0, v0) * v0 @ v0.T + 1/np.vdot(v1, v1) * v1 @ v1.T + 1/np.vdot(v2, v2) * v2 @ v2.T)

P

array([[ 0.5,  0. ,  0. , -0.5],
       [ 0. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ,  0. ],
       [-0.5,  0. ,  0. ,  0.5]])

In [23]:
# Bestemmelse af Px, og dermed projektionen af x på samlingen:
x = np.array([4.0, 3.0, 2.0, 1.0])[:, np.newaxis]

Px = P @ x
Px

array([[ 1.5],
       [ 3. ],
       [ 2. ],
       [-1.5]])

# c) Bekræftelse af at $v_3$ givet ved $x - Px$ er ortogonal med de andre vektorer $v_1, v_2$ og $v_3$

In [24]:
# Angivelse af v3
v3 = x - Px
v3

array([[2.5],
       [0. ],
       [0. ],
       [2.5]])

In [25]:
# Jeg bestemmer nu det ydre produkt mellem v3 og de 3 andre vektorer

np.vdot(v0, v3), np.vdot(v1, v3), np.vdot(v2, v3)

(0.0, 0.0, 0.0)

Da de 3 ydre produkter er = 0, så vil v3 kunne være en del af samlingen, og vil hvis den er, også danne en ortogonal basis.

# d) Dannelse af ortonormal basis ud fra de 4 vektorer

Da de 4 vektorer allerede danner en ortogonal basis, så skal jeg blot normalisere vektorerne, for at bestemme en ortonormal basis. 

Disse 4 enhedsvektorer vil tilsammen danne en ortonormal basis, da:

(1) De har lige så mange indgange som der er vektorer.

(2) De er ortogonale på hinanden allesammen.

(3) Alle vektorer har 2-normen = 1.

(4) Ingen af vektorerne = 0.

In [26]:
# Jeg normaliserer vektorerne
v0e = v0/np.linalg.norm(v0)
v1e = v1/np.linalg.norm(v1)
v2e = v2/np.linalg.norm(v2)
v3e = v3/np.linalg.norm(v3)

v0e, v1e, v2e, v3e

(array([[ 0.5],
        [-0.5],
        [ 0.5],
        [-0.5]]),
 array([[ 0.5],
        [ 0.5],
        [-0.5],
        [-0.5]]),
 array([[0.        ],
        [0.70710678],
        [0.70710678],
        [0.        ]]),
 array([[0.70710678],
        [0.        ],
        [0.        ],
        [0.70710678]]))

For at bekræfte at dette faktisk er en ortonormal samling, så samler jeg dem til en ortogonal matrice, og laver dens grammatrice. Hvis denne grammatrice giver mig en identitetsmatrice, så er det en ortonormal samling.

In [27]:
# Jeg laver matricen ud af vektorerne

B = np.hstack((v0e, v1e, v2e, v3e))

In [28]:
# Jeg kan nu bestemme grammatricen ud fra formlen: G = V^tV
G = B.T @ B
G

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Det er nu bekræftet at dette er en ortonormal basis.